bayabill/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^billing/', include('billing.urls', namespace='billing')),
]

urlpatterns += i18n_patterns(
    url(r'^', include('account.urls', namespace='account')),
    url(r'^', include('web.urls', namespace='web')),
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

web/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        r'^$',
        views.index,
        name='home',
    ),
    url(
        r'^(?P<category_url_key>[\w-]+)/(?P<url_key>[\w-]+)',
        views.product,
        name='product',
    ),
    url(
        r'^(?P<url_key>[\w-]+)',
        views.category,
        name='category',
    ),
]

web/templates/web/category.html
{% extends 'web/layout.base.html' %}
{% block title %}{{ category.meta_title }}{% endblock %}
{% block content %}
    <h1>{{ category.title }}</h1>
    {% for product in products %}
        <ul>
            <li>
                <a href="{% url 'web:product' category.url_key product.url_key %}">
                {{ product.title }}
                </a>
            </li>
        </ul>
    {% endfor %}
{% endblock %}

web/templates/web/layout.base.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="{{ request.LANGUAGE_CODE }}">

<head>
    <meta charset="utf-8" />
    <title>{% block title %}{% endblock %}</title>
    {% if page_description %}<meta name="description" content="{{ page_description }}" />{% endif %}
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css" />
    {% block css %}{% endblock %}
    {% block jshead %}{% endblock %}
</head>

<body>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
    {% block jsbody %}{% endblock %}
</body>

</html>

web/templates/web/product.html
{% extends 'web/layout.base.html' %}
{% block title %}{{ product.meta_title }}{% endblock %}
{% block content %}
    <h1>{{ product.title }}</h1>
    <p>{{ product.description }}</p>
{% endblock %}